'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var GEOLOCATION_GET_POSITION = exports.GEOLOCATION_GET_POSITION = 'GEOLOCATION_GET_POSITION';
var GEOLOCATION_POSITION_CHANGED = exports.GEOLOCATION_POSITION_CHANGED = 'GEOLOCATION_POSITION_CHANGED';
var GEOLOCATION_WATCH_POSITION_STOPPED = exports.GEOLOCATION_WATCH_POSITION_STOPPED = 'GEOLOCATION_WATCH_POSITION_STOPPED';