export const GEOLOCATION_GET_POSITION = 'GEOLOCATION_GET_POSITION'
export const GEOLOCATION_POSITION_CHANGED = 'GEOLOCATION_POSITION_CHANGED'
export const GEOLOCATION_WATCH_POSITION_STOPPED = 'GEOLOCATION_WATCH_POSITION_STOPPED'
